@echo off
echo Starting FounderOS Backend...
cd backend
if not exist node_modules (
    echo Installing dependencies...
    call npm install --legacy-peer-deps
)
echo Generating Prisma client...
call npx prisma generate
if not exist prisma/dev.db (
    echo Creating database...
    call npx prisma migrate dev --name init
    echo Seeding database...
    call npm run seed
)
echo Starting backend server...
call npm run dev

